# This file was generated by GoReleaser. DO NOT EDIT.
cask "llml" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_x86_64.tar.gz",
          verified: "github.com/flyingnobita/llml/releases/download"
      sha256 "91e99998176fa9a1798d528ad296ef0b4c103e449a1bcee7b590aeb4cac51ebb"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_arm64.tar.gz",
          verified: "github.com/flyingnobita/llml/releases/download"
      sha256 "569cc0323a9ce359ed12f40ffb1f419acc11a6be330049e69b380ace1786c34c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_x86_64.tar.gz",
          verified: "github.com/flyingnobita/llml/releases/download"
      sha256 "19179282af4ca9cc66f528ed2cab0065aecb8a41648068ced18131ad2cf7c0f6"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_arm64.tar.gz",
          verified: "github.com/flyingnobita/llml/releases/download"
      sha256 "13589aaa34ea0642c6bd9b4a56d31b5caabe2b37668b93a34994f2ea591ea979"
    end
  end

  name "llml"
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"

  license "MIT"

  livecheck do
    skip "Version is updated by GoReleaser on each release."
  end

  binary "llml"

  # No zap stanza required
end
