# This file was generated by GoReleaser. DO NOT EDIT.
cask "llml" do
  version "0.3.3"

  on_macos do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f45d561c2253df98d44b341b917994018484b586b51e79f923c6457d54786330"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Darwin_arm64.tar.gz"
      sha256 "6cf250b0b14e85e9f801a95fe1a0b3727e7bffd5f4c8b0a0e5fce7750b67b07e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_x86_64.tar.gz"
      sha256 "6ea06a237e321e7f230d323f189d280b3f46a11bf22421ea11f36a6a2fafaab0"
    end
    on_arm do
      url "https://github.com/flyingnobita/llml/releases/download/v#{version}/llml_#{version}_Linux_arm64.tar.gz"
      sha256 "04354dc0f43b99c8e125c5dc9757d31b8d840a4440812f6faea430c5e9c2c06f"
    end
  end

  name "llml"
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llml"

  # No zap stanza required

end
