# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llml < Formula
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.7/llml_0.2.7_Darwin_x86_64.tar.gz"
      sha256 "b73ad8338fb8022f53a5d003a4b3d14293eb78b76422c71c8aa47204e6a7a6a2"

      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.7/llml_0.2.7_Darwin_arm64.tar.gz"
      sha256 "14b8a050417ee0f70ea44c018faaf68b1a5ca8d68332e6bb3347e6b00a7a6580"

      define_method(:install) do
        bin.install "llml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.7/llml_0.2.7_Linux_x86_64.tar.gz"
      sha256 "1cfe3b7f8887648e89259d526afe8a720216a1cb4106b2fcf41221d1a80c64fc"
      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.7/llml_0.2.7_Linux_arm64.tar.gz"
      sha256 "1ab58712d2aee68775cdc740f1e1b958eb98715268e8b8e39627dc2791b570f4"
      define_method(:install) do
        bin.install "llml"
      end
    end
  end
end
