# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llml < Formula
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.3/llml_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "7a6b2183da675c729417b8de5f225f7e8c0babf17da3793d6327ee4522d7be14"

      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.3/llml_0.2.3_Darwin_arm64.tar.gz"
      sha256 "f9287bf33849a9ca3f3b0124507b3e260b43871d65563287f3e9dbfb1c9e9597"

      define_method(:install) do
        bin.install "llml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.3/llml_0.2.3_Linux_x86_64.tar.gz"
      sha256 "e099bfb077ca9ab0d8bcd2d62fa44b1b5c5925ad8da645294756338d7f585371"
      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.3/llml_0.2.3_Linux_arm64.tar.gz"
      sha256 "87ea9065bdc150c90a48cc6c85e60c82f2d80acb7d6e4000f0836fdc163276f3"
      define_method(:install) do
        bin.install "llml"
      end
    end
  end
end
