# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llml < Formula
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.5/llml_0.2.5_Darwin_x86_64.tar.gz"
      sha256 "a7d1ef5da941ced81b1e97466cbe9c7192f960f0735fe503a7fbaf1d58d2f57e"

      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.5/llml_0.2.5_Darwin_arm64.tar.gz"
      sha256 "738655653f1468daeb31bbfd668f1d51a857d57600e12521fb9deb422e9d7e6b"

      define_method(:install) do
        bin.install "llml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.5/llml_0.2.5_Linux_x86_64.tar.gz"
      sha256 "23cb2ae155e6fa7f6d9f3154c4d478eda88a77f6d704b29eaebd12aa8c5a290b"
      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.5/llml_0.2.5_Linux_arm64.tar.gz"
      sha256 "3f9fe31b3a413640c3444a89c01de648cc75bfe474a223102a77acc8f5964b3a"
      define_method(:install) do
        bin.install "llml"
      end
    end
  end
end
